import type { GeneratedDocument } from '../../../../product/sections/documents/types'
import { FileText, ClipboardCheck, Truck, Package, Download, Eye, ExternalLink, Trash2 } from 'lucide-react'

export interface DocumentRowProps {
  document: GeneratedDocument
  onView?: () => void
  onDownload?: () => void
  onDelete?: () => void
  onViewSource?: () => void
}

function getDocumentIcon(type: GeneratedDocument['documentType']) {
  switch (type) {
    case 'purchase-order-pdf':
      return FileText
    case 'inspection-brief':
      return ClipboardCheck
    case 'shipping-manifest':
      return Truck
    case 'packing-list':
      return Package
    default:
      return FileText
  }
}

function getDocumentBadgeClasses(type: GeneratedDocument['documentType']) {
  switch (type) {
    case 'purchase-order-pdf':
      return 'bg-indigo-100 text-indigo-700 dark:bg-indigo-900/30 dark:text-indigo-300'
    case 'inspection-brief':
      return 'bg-cyan-100 text-cyan-700 dark:bg-cyan-900/30 dark:text-cyan-300'
    case 'shipping-manifest':
      return 'bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-300'
    case 'packing-list':
      return 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-300'
    default:
      return 'bg-stone-100 text-stone-700 dark:bg-stone-800 dark:text-stone-300'
  }
}

function getDocumentTypeLabel(type: GeneratedDocument['documentType']) {
  switch (type) {
    case 'purchase-order-pdf':
      return 'Purchase Order'
    case 'inspection-brief':
      return 'Inspection Brief'
    case 'shipping-manifest':
      return 'Shipping Manifest'
    case 'packing-list':
      return 'Packing List'
    default:
      return 'Document'
  }
}

function formatFileSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`
}

function formatDate(dateString: string): string {
  return new Date(dateString).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  })
}

export function DocumentRow({
  document,
  onView,
  onDownload,
  onDelete,
  onViewSource,
}: DocumentRowProps) {
  const Icon = getDocumentIcon(document.documentType)
  const badgeClasses = getDocumentBadgeClasses(document.documentType)
  const typeLabel = getDocumentTypeLabel(document.documentType)

  return (
    <tr className="border-b border-stone-200 dark:border-stone-700 hover:bg-stone-50 dark:hover:bg-stone-800/50 transition-colors">
      {/* Document Name */}
      <td className="px-4 py-3">
        <div className="flex items-center gap-3">
          <div className={`p-2 rounded-lg ${badgeClasses.replace('text-', 'bg-').split(' ')[0]} bg-opacity-20`}>
            <Icon className={`w-4 h-4 ${badgeClasses.split(' ')[1]}`} />
          </div>
          <span className="font-medium text-stone-900 dark:text-stone-100">
            {document.documentName}
          </span>
        </div>
      </td>

      {/* Type */}
      <td className="px-4 py-3">
        <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${badgeClasses}`}>
          {typeLabel}
        </span>
      </td>

      {/* Source Reference */}
      <td className="px-4 py-3">
        <button
          onClick={onViewSource}
          className="text-lime-600 dark:text-lime-400 hover:underline font-medium"
        >
          {document.sourceEntityRef}
        </button>
      </td>

      {/* Generated Date */}
      <td className="px-4 py-3 text-stone-600 dark:text-stone-400">
        {formatDate(document.generatedAt)}
      </td>

      {/* Generated By */}
      <td className="px-4 py-3 text-stone-600 dark:text-stone-400">
        {document.generatedByName}
      </td>

      {/* Size */}
      <td className="px-4 py-3 text-stone-600 dark:text-stone-400">
        {formatFileSize(document.fileSize)}
      </td>

      {/* Actions */}
      <td className="px-4 py-3">
        <div className="flex items-center gap-1">
          <button
            onClick={onDownload}
            className="p-2 text-stone-500 hover:text-stone-700 dark:text-stone-400 dark:hover:text-stone-200 hover:bg-stone-100 dark:hover:bg-stone-700 rounded-lg transition-colors"
            title="Download"
          >
            <Download className="w-4 h-4" />
          </button>
          <button
            onClick={onView}
            className="p-2 text-stone-500 hover:text-stone-700 dark:text-stone-400 dark:hover:text-stone-200 hover:bg-stone-100 dark:hover:bg-stone-700 rounded-lg transition-colors"
            title="Preview"
          >
            <Eye className="w-4 h-4" />
          </button>
          <button
            onClick={onViewSource}
            className="p-2 text-stone-500 hover:text-stone-700 dark:text-stone-400 dark:hover:text-stone-200 hover:bg-stone-100 dark:hover:bg-stone-700 rounded-lg transition-colors"
            title="View Source"
          >
            <ExternalLink className="w-4 h-4" />
          </button>
          <button
            onClick={onDelete}
            className="p-2 text-stone-500 hover:text-red-600 dark:text-stone-400 dark:hover:text-red-400 hover:bg-red-50 dark:hover:bg-red-900/20 rounded-lg transition-colors"
            title="Delete"
          >
            <Trash2 className="w-4 h-4" />
          </button>
        </div>
      </td>
    </tr>
  )
}
